import {trafficReportHtml} from './traffic-html.js';
import {collectionDisplayText} from './collection-display.js';
import {reportTitle,leadershipBrief} from './report-brief.js';
import {reportReadout} from './report-readout.js';
import {decisionReportText,DECISION_LABELS} from './recommendation-decision.js';
const esc=v=>collectionDisplayText(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'Not recorded';
const ratio=(n,d)=>d>0&&n!=null?`${n} / ${d}`:'Not measured';
const pct=(n,d)=>d>0&&n!=null?`${Math.round(n/d*100)}%`:'Not measured';
export const reportActionAnchor=(note,index)=>'selected-action-'+encodeURIComponent(String(note.recommendation_id??index));
export function reportViewUrl(r,view='full',anchor=''){
 const params=new URLSearchParams();
 if(view==='ceo')params.set('view','ceo');
 if(r.period?.chosen)for(const k of ['from','to'])if(r.period[k])params.set(k,r.period[k]);
 return `/api/projects/${encodeURIComponent(r.project.id)}/report${params.size?'?'+params:''}${anchor?'#'+anchor:''}`;
}
export function ceoReportHtml(r){
 const e=r.executive,t=e.totals,readout=reportReadout(e,r.review),brief=leadershipBrief(r,readout);
 const notes=r.review?.notes||[],full=reportViewUrl(r),setup=!!e.localeWarnings?.length;
 const peers=r.review?.comparisons||[];
 const own=peers.find(c=>!c.limited&&c.kind==='owned'&&c.method==='Measured in this cycle'&&c.measured===t.measured&&c.measured>0);
 const comparable=own?peers.filter(c=>c.kind==='competitor'&&c.method==='Measured in this cycle'&&c.measured===own.measured&&!c.limited):[];
 const retrospective=peers.filter(c=>c.kind==='competitor'&&c.method==='Retrospective analysis'&&!c.limited&&c.measured>0).sort((a,b)=>a.name.localeCompare(b.name));
 // Retrospective checks are listed separately, alphabetically, never ranked with original measurements.
 const high=comparable.length?Math.max(...comparable.map(c=>c.named)):null;
 const leaders=comparable.filter(c=>c.named===high);
 const comparison=own?[own,...comparable.sort((a,b)=>b.named-a.named||a.name.localeCompare(b.name)).slice(0,5)]:[];
 const quality=[t.failed?`${t.failed} failed`:null,t.unmeasured?`${t.unmeasured} unmeasured`:null,t.missingChecks?`${t.missingChecks} missing`:null,t.possiblyTruncated?`${t.possiblyTruncated} possibly short answers remain included`:null,t.expectedChecks==null?'Planned coverage unknown':null].filter(Boolean);
 const excerpt=(s,n)=>esc(reportTitle(s,n));
 const action=(n,i)=>{
  const d=n.decision_snapshot,structured=d?.stage&&decisionReportText(d).trim()===n.notes?.trim();
  return `<article class="decision"><p class="eyebrow">${i+1} / ${esc(structured?DECISION_LABELS[d.stage]||'Reviewed decision':'Selected note')} · Selected ${date(n.selected_at)}</p><h3 dir="auto">${esc(reportTitle(n.title))}</h3>${n.outdated?'<p class="warning"><b>Review before sharing:</b> this report copy differs from the current saved decision.</p>':''}${structured?`<p dir="auto">${excerpt(d.change||'Decision not recorded.',330)}</p>${d.purpose?`<p dir="auto"><b>Purpose:</b> ${excerpt(d.purpose,190)}</p>`:''}<p dir="auto"><b>Suggested owner:</b> ${excerpt(d.suggested_owner||'Not recorded. Assign an owner before implementation.',140)}</p>`:`<p dir="auto">${excerpt(n.notes,430)}</p>`}<p class="small"><a href="${esc(reportViewUrl(r,'full',reportActionAnchor(n,i)))}">Full decision, evidence and delivery checks →</a></p></article>`;
 };
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(r.project.name)} | CEO brief</title><style>
 @page{size:A4;margin:16mm 17mm;@bottom-right{content:counter(page);font:9pt sans-serif;color:#526a6f}}*{box-sizing:border-box}body{margin:0;background:#eeeae1;color:#12333b;font:15px/1.5 system-ui,sans-serif}.wrap{max-width:940px;margin:auto;padding:28px}.sheet{background:#fffdf8;padding:42px;margin:22px 0}.mast{display:flex;justify-content:space-between;border-bottom:2px solid #12333b;padding-bottom:12px;font-size:12px;letter-spacing:.12em}.logo{font-weight:800;font-size:19px}.eyebrow{font-size:11px;color:#087e83;text-transform:uppercase;letter-spacing:.08em;font-weight:700}h1,h2{font-family:Georgia,serif;font-weight:400;line-height:1.12}h1{font-size:42px;margin:24px 0 16px}h2{font-size:32px;margin:14px 0 24px}h3{font-size:17px;margin:8px 0}p{margin:12px 0}a{color:#087e83}button,.tools a{padding:10px 15px;border:1px solid #12333b;background:#12333b;color:white;font:inherit;text-decoration:none;border-radius:4px;cursor:pointer}.tools{display:flex;gap:12px;flex-wrap:wrap}.metrics{display:flex;gap:12px;margin:24px 0}.metric{flex:1;background:#e8efeb;padding:15px}.value{font-size:32px;font-weight:700;display:block}.metric small{display:block;margin-top:5px}.small{font-size:12px;color:#526a6f}.insight{border-top:1px solid #cbd8d3;padding:10px 0}.insight p{margin:7px 0}.warning{background:#fff1d7;border-left:4px solid #a66920;padding:12px;font-size:13px}.decision{border-top:2px solid #cad8d4;padding:8px 0 14px}.decision p{font-size:13px}.callout{background:#e8efeb;padding:15px;margin:20px 0}table{width:100%;border-collapse:collapse;font-size:13px}th{text-align:left;color:#526a6f;font-size:11px;text-transform:uppercase}td,th{padding:12px 7px;border-bottom:1px solid #cbd8d3;vertical-align:top}.own{background:#e8efeb}td:first-child{width:50%}td small{display:block;color:#526a6f;font-size:10px;overflow-wrap:anywhere}.foot{border-top:1px solid #cad8d4;padding-top:12px;margin-top:24px;font-size:11px;color:#526a6f}h1,h2,h3,p,td{overflow-wrap:anywhere}p{orphans:3;widows:3}@media(max-width:600px){.wrap{padding:12px}.sheet{padding:22px}.metrics{flex-direction:column}h1{font-size:34px}}@media print{body{background:white;font-size:11pt}.wrap{max-width:none;padding:0}.tools{display:none}.sheet{padding:0;margin:0;background:white;break-before:page}.sheet:first-of-type{break-before:auto}h1{font-size:31pt}h2{font-size:25pt}.metric{padding:12px}.value{font-size:27pt}.decision{break-inside:avoid}.insight,.callout,tr{break-inside:avoid}h2,h3,.eyebrow{break-after:avoid}.decision{padding:4px 0 7px}.decision p{font-size:9.5pt;line-height:1.35;margin:7px 0}.decision h3{font-size:12pt;margin:6px 0}.foot{margin-top:14px}.competitive p{margin:8px 0}.competitive td,.competitive th{padding:8px 7px}.competitive .callout{margin:14px 0;padding:12px}.small{font-size:9pt}*{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
 </style></head><body><main class="wrap"><nav class="tools"><button onclick="window.print()">Print / save PDF</button><a href="${esc(full)}">Full report and evidence appendix</a><a href="/api/projects/${esc(r.project.id)}/report/prepare">Prepare recommendations</a></nav>
 <section class="sheet"><div class="mast"><span class="logo">CITED</span><span>CEO BRIEF</span></div><p class="eyebrow">${esc(r.project.domain)} · Prepared ${date(r.generatedAt)}</p><h1>${esc(r.project.name)}<br>AI visibility. Next decisions.</h1><p class="small">Measurement ${esc(e.measurement?.id||'not recorded')} · ${date(e.cycle)} · ${e.measuredQuestions} measured questions${r.period?.chosen?` · Report dates ${date(r.period.from)} to ${date(r.period.to)}`:''}</p>
 ${setup?`<p class="warning"><b>Diagnostic results only. Correct collection settings before presenting performance conclusions.</b> ${e.localeWarnings.map(esc).join(' ')}</p>`:''}
 <div class="metrics"><div class="metric"><span class="value">${pct(t.named,t.measured)}</span><b>Brand named</b><small>${ratio(t.named,t.measured)} measured answers</small></div><div class="metric"><span class="value">${pct(t.cited,t.measured)}</span><b>Website cited</b><small>${ratio(t.cited,t.measured)} measured answers</small></div><div class="metric"><span class="value">${e.coveredQuestions} / ${e.measuredQuestions}</span><b>Questions with presence</b><small>At least one naming or citation</small></div></div>
 <div class="insight"><b>What changed</b><p>${esc(brief.change)}</p></div><div class="insight"><b>What matters</b><p dir="auto">${esc(brief.matters)}</p></div><div class="insight"><b>The next decision</b><p>${esc(brief.next.replace('below','in the full report'))}</p></div>
 <p class="small">Naming and citation overlap and can have equal totals. They are different outcomes. These are collected answer samples, not market share or a revenue forecast.</p><p class="small"><b>Coverage:</b> ${t.measured} measured answers${t.expectedChecks!=null?` / ${t.expectedChecks} expected checks`:''}. ${esc(quality.join(' · ')||'No collection issue flagged by available checks.')}</p><footer class="foot">Evidence links require Cited access. Share the full report PDF alongside this brief for readers without access.</footer></section>
 <section class="sheet competitive"><p class="eyebrow">02 / Competitive context</p><h2>Who appears alongside you?</h2>${setup?'<p class="warning">Collection settings need correction. Do not use this comparison as a validated market baseline.</p>':''}
 ${comparable.length?`<p>${leaders.length>1?'Joint highest':'Highest'} competitor naming count in this matched sample: <b>${leaders.map(c=>esc(c.name)).join(', ')}</b>, ${high} / ${own.measured} answers. Your brand: ${own.named} / ${own.measured}.</p><table><thead><tr><th>Tracked brand</th><th>Named / measured</th><th>Cited / measured</th></tr></thead><tbody>${comparison.map(c=>`<tr class="${c.kind==='owned'?'own':''}"><td>${esc(c.name)}${c.kind==='owned'?' (your brand)':''}<small>${esc(c.domain||'Domain not recorded')}</small></td><td>${ratio(c.named,c.measured)}</td><td>${ratio(c.cited,c.measured)}</td></tr>`).join('')}</tbody></table><p class="small">Your brand plus up to five competitors, ordered by naming count. Equal counts are ties. Only brands measured in this cycle across the full answer sample are compared here.</p>`:retrospective.length?'<p>No full-sample competitor comparison from the original measurement is available. The later checks below provide additional context.</p>':'<div class="callout">No matched competitor comparison is available for this cycle. Confirm competitors and review answer coverage before making competitive claims.</div>'}
 ${retrospective.length?`<h3>Competitors checked after collection</h3><p class="small">Retrospective analysis: saved answers from this measurement were checked using the competitor names and aliases recorded at review time. No new engine answers were collected. These checks are separate from the original measurement and do not establish a trend.</p><table aria-label="Retrospective competitor checks"><thead><tr><th>Competitor / reviewed</th><th>Named / checked</th><th>Cited / checked</th></tr></thead><tbody>${retrospective.slice(0,5).map(c=>`<tr><td>${esc(c.name)}<small>${esc(c.domain||'Domain not recorded')} · ${date(c.reviewedAt)}</small></td><td>${ratio(c.named,c.measured)}</td><td>${ratio(c.cited,c.measured)}</td></tr>`).join('')}</tbody></table><p class="small">${retrospective.length>5?`${retrospective.length-5} more in the full report. `:''}Listed alphabetically. Each denominator is the number of stored answers checked for that competitor. Equal counts alone do not prove identical answer coverage.</p>`:''}
 <p class="small">Other tracked brands and limited samples remain in the full report. This is not a market ranking or evidence of why an engine selected a brand.</p>
 <div class="callout"><b>Questions define the scope</b><p>${readout.origins.map(x=>`${esc(x.label)}: ${x.questions} / ${e.questions.length}`).join(' · ')||'Question origins not recorded.'}</p><p class="small">Search Console can support Google search demand for the original query. It does not measure AI demand. Manual and site-suggested questions are research hypotheses.</p></div><h3>How to use this comparison</h3><p>Inspect the answers for commercially relevant questions. Compare the cited pages with your existing content before commissioning changes. A higher naming count alone does not identify the cause.</p><footer class="foot"><a href="${esc(full)}">Full report: question results, language coverage, collection limits and evidence</a></footer></section>
 <section class="sheet"><p class="eyebrow">03 / Traffic outcomes</p>${trafficReportHtml(r.traffic,{compact:true})}<footer class="foot">AI visibility shows appearances in collected answers. GA4 shows identifiable visits and recorded actions. Neither measure substitutes for the other.</footer></section>
 <section class="sheet"><p class="eyebrow">04 / Decisions to take forward</p><h2>Turn the findings into work.</h2><p class="small">Up to three selected decisions, in report order, not a priority ranking. These are shortened reading notes. Open the full decision for its page, supporting evidence, constraints and completion checks before implementation. Suggested owners are not assignments.</p>${setup?'<p class="warning">Correct collection settings before using these decisions as conclusions from this measurement.</p>':''}
 ${notes.length?notes.slice(0,3).map(action).join(''):'<div class="callout"><b>No reviewed decisions selected yet.</b><p>Review the evidence and existing pages, then select supported recommendations. Automated investigations are not approved implementation instructions.</p></div>'}
 ${notes.length>3?`<p class="small">${notes.length-3} additional selected decision${notes.length-3===1?'':'s'} in the full report.</p>`:''}<footer class="foot"><b>Then measure again.</b> Record publication dates and repeat the same questions, engines and market settings. Compare naming and citation separately. Later movement alone does not prove that the edits caused it.<p><a href="${esc(full)}">Open full report and evidence appendix →</a> · Cited · ${date(r.generatedAt)}</p></footer></section></main></body></html>`;
}
