const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function reportRange(query={}){
 const p=new URLSearchParams();
 for(const key of ['from','to'])if(typeof query[key]==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(query[key])&&Number.isFinite(Date.parse(query[key]+'T00:00:00Z'))&&new Date(query[key]+'T00:00:00Z').toISOString().slice(0,10)===query[key])p.set(key,query[key]);
 return p;
}
export function reportLoadingHtml(project,query={}){
 const q=reportRange(query);if(query.view==='ceo')q.set('view','ceo');if(query.detail==='1')q.set('detail','1');
 const target=`/api/projects/${Number(project.id)}/report${q.size?'?'+q.toString():''}`;
 const back=`/api/projects/${Number(project.id)}/report/prepare${reportRange(query).size?'?'+reportRange(query).toString():''}`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Preparing ${esc(project.name)} report | Cited</title><style>
 *{box-sizing:border-box}body{margin:0;background:#f5f3ed;color:#12333b;font:16px/1.6 system-ui,sans-serif}main{max-width:720px;margin:8vh auto;padding:32px}.brand{font-weight:800;letter-spacing:.15em;color:#087e83}h1{font:42px/1.15 Georgia,serif}h2{font-size:16px}.card{padding:24px;background:white;border:1px solid #cbd8d3;border-radius:12px}.muted{font-size:14px;color:#526a6f}a{color:#087e83}button{font:inherit;padding:12px 20px;border:0;border-radius:6px;background:#12333b;color:white;cursor:pointer}.pulse{width:38px;height:38px;border:3px solid #d4e4df;border-top-color:#087e83;border-radius:50%;animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.pulse{animation:none}}blockquote{margin:28px 0;font:25px/1.4 Georgia,serif}li{margin:8px 0}[hidden]{display:none!important}@media(max-width:600px){main{padding:22px;margin:2vh auto}h1{font-size:32px}}</style></head><body><main data-report-target="${esc(target)}"><p class="brand">CITED</p><p>${esc(project.name)} · ${query.view==='ceo'?'Executive brief':'Full report'}</p><h1>Your evidence, ready to share.</h1><div class="card"><div class="pulse" aria-hidden="true"></div><p role="status" id="reportStatus">Requesting your report…</p><p class="muted" id="elapsed">0 seconds elapsed</p><h2>What this report brings together</h2><ul><li>Stored AI answers and measurement coverage</li><li>Selected recommendations and supporting evidence</li><li>Available Search Console context and Analytics data</li></ul><p class="muted">This is a description of the report contents, not a live task checklist. No new AI checks are run.</p><button id="retry" hidden>Try again</button></div><blockquote id="reportTip">“Not another dashboard. A to-do list.”</blockquote><p class="muted">Cited reporting tips</p><a href="${esc(back)}">← Back to report preparation</a><noscript><p>JavaScript is off. <a href="${esc(target)}">Open the report directly</a>.</p></noscript></main><script src="/report-loading.js?v=80"></script><script src="/context-help.js?v=90" defer></script></body></html>`;
}
