import {trafficQualityHtml} from './traffic-quality.js';
import {isCareersPath} from './traffic-event-context.js';
import {collectionDisplayText} from './collection-display.js';
const esc=v=>collectionDisplayText(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function eventBreakdownHtml(data,{compact=false}={}) {
 if(data.eventState!=='ready')return `<p class="note small">Key-event detail ${data.eventState==='mismatch'?'does not reconcile with the traffic total and is withheld.':'is unavailable. Sync Analytics to request it.'} Confirm event definitions with the Analytics owner before calling these leads or applications.</p>`;
 const rows=data.events||[];
 return `<h3>What those key events were</h3>${rows.length?`<table><thead><tr><th>Recorded GA4 event name</th><th>Key events</th></tr></thead><tbody>${rows.slice(0,compact?3:10).map(r=>`<tr><td>${esc(r.name)}</td><td>${Number(r.count).toLocaleString('en-GB',{maximumFractionDigits:6})}</td></tr>`).join('')}</tbody></table>${rows.length>(compact?3:10)?`<p class="note small">Top ${compact?3:10} of ${rows.length} event names shown.</p>`:''}`:'<p>No key events recorded in this covered period.</p>'}<p class="note small">Exact event names from GA4, using the same dates and AI referral filter. Counts reconcile with the key-event total. Names alone do not verify completed applications, qualified leads or unique customers. Confirm each event’s trigger with the Analytics owner.</p>`;
}
export function eventContextHtml(data,{compact=false}={}) {
 const careerPages=(data.pages||[]).filter(p=>isCareersPath(p.page)&&p.conversions>0);
 const warning=careerPages.length?`<p class="callout warning">Review before calling these customer leads: ${careerPages.reduce((n,p)=>n+p.conversions,0)} key events are associated with sessions starting on paths labelled careers or jobs. Those counts remain in the total. The landing page does not establish what the event was for.</p>`:'';
 const note='<p class="note small">One action can trigger multiple event names. These aggregate counts cannot establish overlap or unique leads. Ask the Analytics owner to confirm each trigger, form destination and duplicate-firing checks. No events have been excluded or relabelled as verified leads.</p>';
 if(compact)return warning+note;
 const rows=data.eventPages||[];
 const detail=data.eventContextState==='ready'?(rows.length?`<h3>Events by session landing page</h3><table><thead><tr><th>GA4 event name</th><th>Session landing page</th><th>Key events</th></tr></thead><tbody>${rows.slice(0,10).map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.page)}</td><td>${Number(r.count).toLocaleString('en-GB',{maximumFractionDigits:6})}</td></tr>`).join('')}</tbody></table><p class="note small">Top ten event/page combinations shown. Complete counts match the event and landing-page totals for this period. A landing page is the session’s entry page, not necessarily where the event happened.</p>`:''):`<p class="note small">Event/page detail ${data.eventContextState==='mismatch'?'does not reconcile and is withheld.':'is unavailable. Sync Analytics to request it.'}</p>`;
 return warning+detail+note;
}
export function trafficReportHtml(t,{compact=false}={}){
 const data=t||{state:'needs_sync',why:'Sync Analytics to load verified traffic outcomes.'};
 const known=data.total!=null;
 return `<section class="traffic-outcomes"><h2>What AI traffic delivered</h2>${!known?`<p class="callout">${esc(data.why||'Traffic is unavailable. This is not zero visits.')}</p>`:`<p><b>${Number(data.quality?.state==='ready'?data.quality.sessions:data.total).toLocaleString('en-GB')} sessions</b> · <b>${Number(data.conversions).toLocaleString('en-GB')} key events</b>${data.currency?` · ${Number(data.revenue).toLocaleString('en-GB',{maximumFractionDigits:6})} ${esc(data.currency)} recorded revenue`:''}</p><p class="note small">GA4 property ${esc(data.propertyId)} · Covered ${esc(data.coveredFrom)} to ${esc(data.coveredTo)} · Last successful sync ${esc(data.syncedAt?new Date(data.syncedAt).toISOString():'Not recorded')}</p>${data.state==='partial'?`<p class="callout warning">Partial coverage. Requested ${esc(data.from)} to ${esc(data.to)}. Sync Analytics before presenting this as a complete ${data.days}-day period.</p>`:''}${!data.currency?'<p class="note small">Revenue currency was not returned. Monetary totals are withheld.</p>':''}${data.sources.length?`<table><thead><tr><th>AI referral source</th><th>Sessions</th><th>Key events</th></tr></thead><tbody>${data.sources.slice(0,compact?3:10).map(s=>`<tr><td>${esc(s.source)}</td><td>${s.sessions}</td><td>${s.conversions}</td></tr>`).join('')}</tbody></table>`:''}${trafficQualityHtml(data.quality)}${eventBreakdownHtml(data,{compact})}${eventContextHtml(data,{compact})}${!compact&&data.pages.length?`<h3>Landing pages to review</h3><table><thead><tr><th>Landing page</th><th>Sessions</th><th>Key events</th></tr></thead><tbody>${data.pages.slice(0,10).map(p=>`<tr><td>${esc(p.page)}</td><td>${p.sessions}</td><td>${p.conversions}</td></tr>`).join('')}</tbody></table>`:''}<p class="note small">${compact?'Up to three sources shown.':'Up to ten sources and landing pages shown.'} ${data.quality?.state==='ready'?'The headline session count comes from GA4’s period aggregate. Source and landing-page counts come from the detailed query.':'Totals include all matched rows.'} A recorded zero does not establish that event or revenue tracking is configured correctly.</p>`}<p class="note small">GA4 AI Assistant traffic and recognised AI source domains are collected in one query, without adding overlapping series. Key events count recorded actions, not unique leads or converted sessions. No conversion rate is inferred. Traffic without an identifiable AI source is not captured here. These dates and denominators are separate from AI visibility checks, and do not prove the effect of content changes.</p></section>`;
}
